### ISSUE TITLE
Why the error message 'NoEnginesRegistered:` Can't build targets without any engines' ?

### ISSUE THREAD

**Issue by hellojinwoo** [RSNirwan/PortfolioAllocationUsingGPLVM#2]
<h3> Problem </h3>
While runninng codes in the file 'latent_space_embedding.ipynb', I encountered the error message 

> NoEnginesRegistered:` Can't build targets without any engines

<h3> Explanation </h3>

1. I am running this codes on my local computer (laptop) with jupyter lab. Jupyter lab is like an expansion version of jupyter notebook.
2. I opened two terminals (cmd) ; with one, I run the code  ` ipcluster start -n 4` as you instructed in the file, and with the other, I opened the jupyter lab and executed the codes.
3. However, this part of codes `with rc[:].sync_imports(): `  produced the error saying 
> NoEnginesRegistered: Can't build targets without any engines

What should I do to solve this problem? Thank you

**Comment by rsnirwan** [comment]
Hi hellojinwoo,

Make sure to cd into the GPLVM folder before you run `ipcluster start -n 4`.
Have you enabled serverextensions and nbextensions?  
Try the following before you start jupyter:

`jupyter serverextension enable --py ipyparallel`
`jupyter nbextension install --py ipyparallel`
`jupyter nbextension enable ipyparallel --py`

Otherwise you can use any other library to run the code in parallel. Or reduce the number of data points and the number of kernels and run the code sequentially.

**Comment by hellojinwoo** [comment]
> Make sure to cd into the GPLVM folder before you run `ipcluster start -n 4`.

This line totally works for me! Thank you
